language: python
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo add-apt-repository --yes ppa:fontforge/fontforge
- sudo apt-get update -qq
- sudo apt-get install python-fontforge ttfautohint swig libicu-dev
- cp /usr/lib/python2.7/dist-packages/fontforge.* "$HOME/virtualenv/python2.7.9/lib/python2.7/site-packages"
# See issue travis-ci/travis-ci#1379
- sudo apt-get install -qq g++-4.8
- export CXX="g++-4.8" CC="gcc-4.8"
- git clone https://github.com/khaledhosny/ots
- cd ots
- ./autogen.sh
- ./configure
- make
- sudo make install
- cd ..
install:
- pip install pyicu
- pip install git+https://github.com/behdad/fontTools.git
- pip install git+https://github.com/googlefonts/fontcrunch.git
- pip install git+https://github.com/googlefonts/fontbakery.git
before_script:
- mkdir -p builds/$TRAVIS_COMMIT
script: (set -o pipefail; PATH=/home/travis/virtualenv/python2.7.9/bin/:$PATH fontbakery-build.py . 2>&1 | tee -a    builds/$TRAVIS_COMMIT/buildlog.txt)
after_script:
- PATH=/home/travis/virtualenv/python2.7.9/bin/:$PATH fontbakery-report.py builds/$TRAVIS_COMMIT
- rm -rf builds/$TRAVIS_COMMIT/sources
- rm -rf builds/$TRAVIS_COMMIT/build.state.yaml
- PATH=/home/travis/virtualenv/python2.7.9/bin/:$PATH fontbakery-travis-deploy.py
branches:
 only:
 - master
